name: Iris ML Pipeline with MLflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install cloud-ml-sdk==0.3.71 --no-deps
          pip install cloud-ml-common==0.0.2
          pip install cml==0.0.1 --no-deps

      - name: Train model with hyperparameter tuning
        run: |
          python train.py > metrics.txt
          tail -n 10 metrics.txt > report.md

      - name: Comment Report
        env:
          REPO_TOKEN: ${{ secrets.CML_TOKEN }}
        run: |
          pip install cml
          cml comment create report.md --token $REPO_TOKEN

